(define (domain convbelt)
    (:requirements :strips :equality)
    (:predicates (Pickable ?o)
                 (Grasp ?g)
                 (GraspConf ?gc)
                 (GraspTransform ?o ?g ?q)
                 (EmptyArm)
                 (Holding ?o ?g ?gc)
                 (BaseConf ?q)
                 (PlaceConf ?o ?p ?q)
                 (BTraj ?o ?g ?pick_q ?q2 ?traj)
                 (AtPose ?o ?p)
                 (AtConf ?r ?q)
                 (InLoadingRegion ?o)
                 (InLoading ?o)
                 (Region ?r)
                 (Contained ?p ?r)
                 (Pose ?o ?p)
                 (Robot ?robot)
                 (Picked ?o)
                 (Placed ?o)
                 ;(UnsafeBTraj ?o ?g ?pick_q ?place_q ?t)
                 ;(UnsafeBTraj ?q)
                 ;(TrajPoseCollision ?q ?t ?o2 ?p2)
                 (TrajPoseCollision ?holding_o ?grasp ?pick_q ?placed_o ?placed_p ?place_q ?traj)
                 (UnsafeBTraj ?holding_o ?grasp ?pick_q ?place_q ?traj)
                 )

    (:action pickup
    :parameters (?o ?g ?absq)
    :precondition (and (EmptyArm)
                       (Pickable ?o)
                       (Grasp ?g)
                       (BaseConf ?absq)
                       (GraspTransform ?o ?g ?absq)
                       (not (InLoadingRegion ?o))
                       )
    :effect (and (Picked ?o) (not (EmptyArm))))

    (:action place
    :parameters(?o ?g ?pick_q ?placement ?q2 ?traj)
    :precondition (and (Pickable ?o)
                       (Picked ?o)
                       ;(Grasp ?g)
                       ;(BaseConf ?pick_q)
                       (GraspTransform ?o ?g ?pick_q)
                       ;(BaseConf ?q2)
                       (Pose ?o ?placement)
                       (PlaceConf ?o ?placement ?q2)
                       (BTraj ?o ?g ?pick_q ?q2 ?traj)
                       (not (UnsafeBTraj ?o ?g ?pick_q ?q2 ?traj))
                       )
    :effect (and (EmptyArm) (not (Picked ?o)) (InLoadingRegion ?o) (AtPose ?o ?placement)))

    (:derived (UnsafeBTraj ?holding_o ?grasp ?pick_q ?place_q ?traj) (
        exists (?placed_o ?placed_p) (and
                        (AtPose ?placed_o ?placed_p)
                        (TrajPoseCollision ?holding_o ?grasp ?pick_q ?placed_o ?placed_p ?place_q ?traj)
                        ;(InLoadingRegion ?placed_o)
                        ;(Picked ?holding_o)
                        ;(BTraj ?holding_o ?grasp ?pick_q ?place_q ?traj)
                        ;(GraspTransform ?holding_o ?grasp ?pick_q)
                        ;(InLoadingRegion ?placed_o)
                        ;(not (= ?holding_o ?placed_o))
                     )
    ))

)


